### PR TITLE
feat!: remove categories from config and instead pass them as base64 encoded json param

### PR DESCRIPTION
**Pull request by aleksasiriski**
**A lot of BREAKING CHANGES**

This PR implements categories (engines to use and their ranking) as an base64 encoded JSON parameter. This means that we do not have the need for predefined categories here (this will be moved to frontend to keep the current ones as they are).

This is the first step towards a distributed network model, allowing faster innovation with less updates for agents (as they're the main self-hosted component) while also allowing us to implement client-side made custom categories (with personal ranking).

Introduction of search types:

- web
- images
- suggestions

Web (before "general") is now separated from image searching.

Old route -> New route:

- `/healthz` -> `/healthz` (same)
- `/versionz` -> `/versionz` (same)
- `/search` -> `/search/web` (requires new `category` param)
- `/search` (category images) -> `/search/images` (requires new `category` param)
- `/suggestions` -> `/search/suggestions` (requires new `category` param)
- `/exchange` -> `/exchange` (same)
- `/currencies` -> `/exchange/currencies`
- `/proxy` -> `/imageproxy`

TODO:
- [x] remove default categories
- [x] add category param (base64 encoded json)
- [x] handle self-hoster disabled engines (return user error)
- [x] fix tests to work with the new code
- [x] rename instances of "general" to "web"
- [x] rename instances of "search" to "websearch"
- [x] update example config

### CODE REVIEW

**Comment by k4lizen** [comment]
Huh I see you're passing the category as a parameter, I didn't realize that was part of the idea

**Comment by k4lizen** [comment]
Yeah okay this makes sense, there is no loss of information like I was worried about in https://github.com/hearchco/agent/discussions/443#discussioncomment-11267391

**Comment by aleksasiriski** [comment]
> Yeah okay this makes sense, there is no loss of information like I was worried about in [#443 (comment)](https://github.com/hearchco/agent/discussions/443#discussioncomment-11267391)

Yeah I ran into the problem that you mentioned there and came up with this solution, but as I realized it would require a lot of params to get it passed from frontend decided to use base64 instead. Now we need to reimplement the categories on frontend and after that we can make UI for users to make custom ones that can be saved in their cookie.

**Review by matijakljajic — DISMISSED** [review]

**Comment by matijakljajic** [comment]
Approved, waiting on frontend for it to be merged.

**Pull request merged**
