### PR TITLE
docs: add docs for setup

### PR DESCRIPTION
**Pull request by allendema**
Adds a README file along with an example systemd unit file (arguments [from here](https://github.com/navidrome/website/blob/5f299635282f652b2a47713ca61f6be6024559e9/content/en/docs/Installation/linux.md?plain=1#L57)).

### CODE REVIEW

**Comment by aleksasiriski** [comment]
Hello there, it seems that formatting is off when looking at the rendered markdown on your branch, probably something to do with the summary tag.

Also, are you sure that you have to chown the binary? Shouldn't it be owned by root but executable by anyone or hearchco user only?

**Comment by allendema** [comment]
Will change formatting to render correctly soon. 

The chown is not necessary but better to run it explicitly. 
Even without chown it will presumably work also.

**Comment by aleksasiriski** [comment]
Isn't it better to be owned by root for security? If it's owned by hearchco user and someone breaks out of the app into the user they could change your binary, while if i's owned by root they cannot even if they break out with that user, correct me if I'm wrong.

**Comment by allendema** [comment]
Markdown should be render now.
My reference for chmod is from [docs/Installation/linux.md?plain=1#L44](https://github.com/navidrome/website/blob/5f299635282f652b2a47713ca61f6be6024559e9/content/en/docs/Installation/linux.md?plain=1#L44) and [usage](https://github.com/navidrome/website/blob/5f299635282f652b2a47713ca61f6be6024559e9/content/en/docs/Usage/security.md#permissions) but you are right.

Feel free to edit that and other things in the branch how you see fit.

**Comment by aleksasiriski** [comment]
Okay, good. I will take this up next week when I get back from Lisbon (WebSummit). My only question, which you of course don't have to answer: why not use docker / podman (or compose) instead of systemd service, since to me it seems that most of the work you describe would be already taken care of?

Regardless of your answer, thanks for your contribution, it is much welcome, I will merge it ASAP.

**Comment by allendema** [comment]
Bare metal generally has worked very well so I like that. Having options is nice.

**Review by aleksasiriski — APPROVED** [review]
LGTM

**Pull request merged**
